<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Md Zabirul Islam">
<meta name="description" content="Development and Validation of a Large Language Model for Generating Fully-Structured Lung Nodule Reports">

<title>Lung Nodule Reporting | Md Zabirul Islam</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em;
  vertical-align: middle;
}
.project-header {
  text-align: center;
  padding: 2rem 0;
  margin-bottom: 2rem;
}
.project-title {
  font-size: 2.5rem;
  font-weight: bold;
  margin-bottom: 1rem;
  
}
.project-subtitle {
  font-size: 1.2rem;
  margin-bottom: 1.5rem;
  opacity: 0.9;
}
.authors {
  font-size: 1.1rem;
  margin-bottom: 0.5rem;
}
.affiliations {
  font-size: 1rem;
  opacity: 0.8;
}
.links-section {
  display: flex;
  justify-content: center;
  gap: 1rem;
  margin: 2rem 0;
  flex-wrap: wrap;
}
.project-link {
  background: transparent;
  color: #495057;
  padding: 0.75rem 1.5rem;
  text-decoration: none;
  border: 2px solid #dee2e6;
  border-radius: 8px;
  font-weight: bold;
  transition: all 0.3s ease;
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
}
.project-link:hover {
  border-color: #750505;
  color: #750505;
  text-decoration: none;
  transform: translateY(-2px);
}
.journal-badge {
  background: #000000;
  color: white;
  padding: 0.75rem 1.5rem;
  border-radius: 25px;
  font-weight: bold;
  display: inline-block;
  margin: 0 0.5rem;
  cursor: default;
}
.section-title {
  font-size: 1.8rem;
  font-weight: bold;
  margin: 2rem 0 1rem 0;
  color: #011627;
  border-bottom: 3px solid #011627;
  padding-bottom: 0.5rem;
}
.architecture-image {
  width: 100%;
  max-width: 1000px;
  margin: 2rem auto;
  display: block;
  border-radius: 10px;
  box-shadow: 0 4px 15px rgba(0,0,0,0.1);
}
.results-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
  gap: 2rem;
  margin: 2rem 0;
}
.result-item {
  text-align: center;
}
.result-image {
  width: 100%;
  border-radius: 10px;
  box-shadow: 0 4px 15px rgba(0,0,0,0.1);
  margin-bottom: 1rem;
}
.abstract-section {
  background: #f8f9fa;
  padding: 2rem;
  border-radius: 10px;
  margin: 2rem 0;
  border-left: 5px solid #750505;
}

/* Mobile Responsive Styles */
@media (max-width: 768px) {
  /* Fix navbar centering on mobile - use flexbox approach */
  .navbar-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
  }
  
  .navbar-brand-container {
    flex: 1;
    display: flex;
    justify-content: center;
    margin: 0 !important;
  }
  
  .navbar-toggler {
    order: 3;
    flex-shrink: 0;
  }
  
  /* Add invisible spacer to balance the toggler */
  .navbar-container::before {
    content: '';
    width: 48px; /* Same width as navbar-toggler */
    height: 1px;
    order: 1;
    flex-shrink: 0;
  }
  
  .project-header {
    padding: 1rem 0;
    margin-bottom: 1rem;
  }
  
  .project-title {
    font-size: 1.8rem !important;
    line-height: 1.3;
  }
  
  .authors {
    font-size: 1rem;
  }
  
  .affiliations {
    font-size: 0.9rem;
  }
  
  .section-title {
    font-size: 1.4rem;
    margin: 1.5rem 0 0.8rem 0;
  }
  
  .abstract-section {
    padding: 1.5rem;
    margin: 1.5rem 0;
  }
  
  .links-section {
    gap: 0.8rem;
    margin: 1.5rem 0;
    padding: 0 1rem;
  }
  
  .project-link, .journal-badge {
    padding: 0.6rem 1rem;
    font-size: 0.9rem;
    margin: 0.25rem;
  }
  
  .results-grid {
    grid-template-columns: 1fr;
    gap: 1.5rem;
    margin: 1.5rem 0;
  }
  
  /* Fix main content padding on mobile */
  main.content {
    padding: 0 1rem !important;
  }
  
  /* Responsive images */
  img {
    max-width: 100%;
    height: auto;
  }
  
  /* Adjust image sizes for mobile */
  img[style*="max-width: 800px"] {
    max-width: 95% !important;
  }
  
  img[style*="max-width: 700px"] {
    max-width: 95% !important;
  }
  
  img[style*="max-width: 650px"] {
    max-width: 95% !important;
  }
  
  img[style*="max-width: 600px"] {
    max-width: 95% !important;
  }
  
  /* Better spacing for mobile */
  div[style*="margin: 3rem 0"] {
    margin: 2rem 0 !important;
  }
  
  div[style*="margin: 2rem 0"] {
    margin: 1.5rem 0 !important;
  }
  
  /* Responsive text containers */
  p[style*="max-width: 900px"],
  p[style*="max-width: 1000px"],
  p[style*="max-width: 800px"] {
    max-width: 100% !important;
    padding: 0 0.5rem;
  }
  
  /* Code blocks responsive */
  pre {
    font-size: 0.8rem;
    overflow-x: auto;
  }
  
  /* Button styling for mobile */
  a[style*="background: #750505"] {
    display: block !important;
    width: 100%;
    max-width: 300px;
    margin: 1rem auto !important;
    text-align: center;
  }
}

@media (max-width: 480px) {
  .project-title {
    font-size: 1.5rem !important;
  }
  
  .section-title {
    font-size: 1.2rem;
  }
  
  main.content {
    padding: 0 0.75rem !important;
  }
  
  .abstract-section {
    padding: 1rem;
  }
  
  .project-link, .journal-badge {
    padding: 0.5rem 0.8rem;
    font-size: 0.85rem;
  }
  
  h3[style*="color: #2E8B57"] {
    font-size: 1.1rem !important;
  }
  
  h4[style*="color: #2E8B57"] {
    font-size: 1rem !important;
  }
}

.results-table { width: 100%; border-collapse: collapse; margin: 1.5rem 0; font-size: 0.95rem; }
.results-table th, .results-table td { border: 1px solid #dee2e6; padding: 0.5rem 0.75rem; text-align: center; }
.results-table th { background: #011627; color: #fff; }
.results-table tr.highlight td { background: #fff8e1; font-weight: bold; }
.table-wrap { overflow-x: auto; }
.stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
.stat-card { background: #f8f9fa; border-radius: 10px; padding: 1rem; text-align: center; border-top: 4px solid #750505; }
.stat-card .num { font-size: 1.6rem; font-weight: bold; color: #011627; }
.stat-card .lbl { font-size: 0.85rem; color: #555; }
.flow { display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center; justify-content: center; margin: 1.5rem 0; }
.flow .step { background: #eef2ff; border: 2px solid #3252b3; border-radius: 10px; padding: 0.6rem 0.9rem; font-weight: 600; font-size: 0.9rem; text-align: center; max-width: 190px; }
.flow .arrow { font-size: 1.3rem; color: #011627; }
.note { font-size: 0.9rem; color: #555; font-style: italic; }
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../files/favicon-512.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/size.css" rel="stylesheet">

<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-3THLGK2G1N"></script>
<script type="text/javascript">
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-3THLGK2G1N', { 'anonymize_ip': true});
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
<header id="quarto-header" class="headroom fixed-top">
  <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
    <!-- <div class="navbar-container container-fluid"> -->
    <div class="navbar-brand-container mx-auto">
      <a class="navbar-brand" href="../../../index.html">
      <span class="navbar-title"><strong>Md Zabirul</strong> Islam</span>
      </a>
    </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
<span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
  <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
</li>  
<li class="nav-item">
  <a class="nav-link" href="../../../Research/research/research.html"> 
<span class="menu-text">Publications</span></a>
</li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects/projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../Zabirul_Islam_CV.pdf" target="_blank"> 
<span class="menu-text">Resume</span></a>
  </li>  
<!--   <li class="nav-item">
    <a class="nav-link" href="../../service/index.html"> 
<span class="menu-text">Service</span></a>
  </li>  --> 
</ul>
          </div>
      </div>
    </nav>
</header>


<div class="project-header">
<div class="container">
  <h2 class="project-title">
    Development and Validation of a Large Language Model for Generating Fully-Structured Lung Nodule Reports
  </h2>

  <div class="authors">
    Md Sayed Tanveer<sup>&dagger;</sup>, <strong>Md Zabirul Islam<sup>&dagger;</sup></strong>, Chuang Niu, Parisa Kaviani, Qing Lyu,
    Mannudeep K. Kalra, Christopher T. Whitlow, Ge Wang
    <div style="font-size: 0.9rem; opacity: 0.8; margin-top: 0.25rem;"><sup>&dagger;</sup> Equal contribution</div>
  </div>

  <div class="affiliations">
    Rensselaer Polytechnic Institute &middot; Massachusetts General Hospital, Harvard Medical School &middot; Wake Forest University School of Medicine
  </div>
</div>

<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">

<main class="content column-page-left container-fluid" id="quarto-document-content" style="max-width: 1200px; margin: 0 auto; padding: 0 2rem; text-align: left;">

  <div class="links-section" style="text-align: center;">
    <span class="journal-badge">Submitted to JAMIA</span>
    <a href="https://arxiv.org/abs/2409.18319" class="project-link" target="_blank">
      <i class="fas fa-file-pdf"></i> Earlier preprint
    </a>
  </div>

  <div class="abstract-section">
    <h2 class="section-title">Overview</h2>
    <p>
      Most radiology reports are dictated as free text. That keeps radiologists fast, but it locks the findings inside prose: a nodule's size,
      location, attenuation, and stability cannot be searched, tracked, or counted without someone reading every report.
    </p>
    <p>
      This work converts free-text lung cancer screening CT reports into <strong>fully structured lung-nodule reports</strong> without changing
      how radiologists dictate. A <strong>dynamic template-constrained decoder</strong> lets a locally hosted open-weight LLM write only values a
      radiologist-designed template allows, so every output is valid by construction. It was validated across two institutions and then extended with
      synthetic fine-tuning so compact models can do the job at a fraction of the token cost. The study covers 7,442 reports (2021&ndash;2023) under
      IRB approval at both institutions.
    </p>
  </div>

  <div class="stat-grid">
    <div class="stat-card"><div class="num">0.976 / 0.969</div><div class="lbl">F1 on two institutions</div></div>
    <div class="stat-card"><div class="num">5,442</div><div class="lbl">LDCT screening reports</div></div>
    <div class="stat-card"><div class="num">30,000</div><div class="lbl">synthetic training reports</div></div>
    <div class="stat-card"><div class="num">84&ndash;87%</div><div class="lbl">fewer tokens after fine-tuning</div></div>
    <div class="stat-card"><div class="num">97.7% &rarr; 100%</div><div class="lbl">JSON-schema validity with grammar</div></div>
  </div>

  <h2 class="section-title">🗂️ Study Design</h2>
  <div style="text-align: center; margin: 2rem 0;">
    <img src="rad_fig1.jpg" class="architecture-image" alt="Two-stage study design">
    <p><strong>Figure 1:</strong> Stage 1 validates dynamic template-constrained decoding on two manually structured 250-report cohorts from separate
    institutions. Stage 2 is a separate controlled experiment on synthetic fine-tuning, using diagnostic chest CT reports that share no report with Stage 1.</p>
  </div>

  <h2 class="section-title">🏗️ Framework and Template</h2>
  <div style="text-align: center; margin: 2rem 0;">
    <img src="rad_fig2.jpg" class="architecture-image" alt="Framework of the dynamic-template-constrained LLM">
    <p><strong>Figure 2:</strong> A free-text report, a system instruction, and a standardized template go in; a structured report with nodule-level
    and report-level fields comes out. The system extracts what the radiologist documented and does not reinterpret images.</p>
  </div>
  <p>
    Two radiologists built a fixed <strong>30-feature template</strong>: 25 nodule-level features (lobe, segment, type, margin, size, stability,
    Lung-RADS, and more), 4 report-level management features, and the nodule count. The decoder first predicts how many nodules the report
    describes, creates that many nodule entries, and then restricts every field to its allowed values (including null).
  </p>
  <div style="text-align: center; margin: 2rem 0;">
    <img src="rad_fig3.jpg" class="architecture-image" alt="Dynamic template-constrained decoding">
    <p><strong>Figure 3:</strong> Standard LLM decoding vs. dynamic template-constrained decoding. The template's special slots (pink) are filled only from
    their candidate sets (green).</p>
  </div>

  <h2 class="section-title">📊 Stage 1: Cross-Institutional Validation</h2>
  <div style="text-align: center; margin: 2rem 0;">
    <img src="rad_fig5.jpg" class="img-fluid" style="max-width: 650px;" alt="Performance on the two labeled datasets">
    <p><strong>Figure 4:</strong> Mean and feature-wise F1 with 95% CIs on both institutions, with and without constrained decoding.</p>
  </div>
  <ul>
    <li>Best configuration (Llama-3.1-405B, constrained): <strong>F1 0.976</strong> (95% CI 0.965&ndash;0.986) and <strong>0.969</strong> (0.958&ndash;0.980),
    with <strong>no formatting or out-of-template errors</strong>.</li>
    <li>Constrained decoding improved every open-weight model tested (Llama-3.1 8B/70B/405B, Qwen-2-72B, Mistral-Large-123B), by 4.5 to 18.4
    percentage points on Institution 1 and 3.9 to 15.3 on Institution 2.</li>
    <li>Constrained Llama-3.1-405B beat GPT-4o by 17.2 points overall and on 26 of 27 features.</li>
  </ul>

  <h2 class="section-title">🔎 Large-Scale Statistics Without Manual Labeling</h2>
  <p>
    Structuring 5,192 consecutive screening reports made population-level analysis automatic. Nodules were more frequent in the upper lobes and the
    right lung, and women had more ground-glass nodules than men (all P &lt; .01). Lung-RADS 2 accounted for 66.0% of reports and Lung-RADS 1 for 22.4%.
    57.9% of nodules averaged under 6 mm, and 85.8% were stable relative to prior exams. These patterns match previously reported distributions.
  </p>

  <h2 class="section-title">⚙️ Stage 2: Synthetic Fine-Tuning for Compact Models</h2>
  <div style="text-align: center; margin: 2rem 0;">
    <img src="rad_fig4.jpg" class="img-fluid" style="max-width: 700px;" alt="Construction of the synthetic fine-tuning corpus">
    <p><strong>Figure 5:</strong> Real lungs/pleura sentences are recombined into new reports, and a 405B teacher produces sparse structured targets:
    30,000 synthetic training reports in total.</p>
  </div>
  <div class="table-wrap">
  <table class="results-table">
    <thead><tr><th>Model</th><th>Unadapted F1</th><th>Fine-tuned F1</th><th>Tokens / report</th></tr></thead>
    <tbody>
      <tr><td>Llama-3.2-1B</td><td>0.124</td><td>0.713</td><td>4,983 &rarr; 730</td></tr>
      <tr><td>Gemma-3-4B</td><td>0.205</td><td>0.746</td><td>5,467 &rarr; 701</td></tr>
      <tr><td>Mistral-7B</td><td>0.404</td><td>0.780</td><td>5,570 &rarr; 843</td></tr>
      <tr class="highlight"><td>Qwen2.5-7B</td><td>0.488</td><td>0.784</td><td>4,685 &rarr; 739</td></tr>
      <tr><td>Llama-3.1-8B</td><td>0.567</td><td>0.764</td><td>4,681 &rarr; 727</td></tr>
      <tr><td>Llama-3.1-70B (QLoRA)</td><td>0.839</td><td>0.757</td><td>4,655 &rarr; 721</td></tr>
    </tbody>
  </table>
  </div>
  <p class="note">250-report test cohort; reference-support-weighted exact-match F1 with 10,000 report-level bootstrap resamples.</p>
  <div style="text-align: center; margin: 2rem 0;">
    <img src="rad_fig6.jpg" class="img-fluid" style="max-width: 700px;" alt="Stage 2 performance, efficiency, and schema validity">
    <p><strong>Figure 6:</strong> (a) Effect of the dynamic template on unadapted models; (b) unadapted vs. fine-tuned F1; (c) token use; (d) raw schema validity.</p>
  </div>
  <ul>
    <li>Fine-tuning improved five of six models and narrowed F1 from 0.124&ndash;0.839 to 0.713&ndash;0.784, while cutting tokens per report by 84.2&ndash;87.2%.</li>
    <li>After fine-tuning, a lightweight sparse grammar changed F1 by less than one point but raised schema-valid outputs from 1,466 to 1,500 of 1,500.
    Once the model has learned the format, the constraint mainly guarantees valid structure.</li>
  </ul>

  <h2 class="section-title">⚠️ Limitations</h2>
  <ul>
    <li>The unadapted Llama-3.1-70B is still numerically best. The benefit of fine-tuning is lower cost at comparable accuracy, not higher accuracy.</li>
    <li>Llama-3.1-70B was adapted with QLoRA while the smaller models were fully fine-tuned, so model size and adaptation method are confounded for that family.</li>
    <li>Retrospective study against report-derived references; effects on clinical workflow and patient outcomes were not assessed.</li>
    <li>The system structures what the radiologist wrote. It does not interpret images, revise Lung-RADS categories, or judge clinical correctness.</li>
  </ul>

  <h2 class="section-title">🚀 Key Contributions</h2>
  <ul>
    <li>Dynamic template-constrained decoding for <strong>variable numbers of linked nodule objects</strong>, with zero formatting errors.</li>
    <li>Cross-institutional validation on 500 manually structured reports from two health systems.</li>
    <li>Automatic population-level nodule statistics from 5,192 consecutive screening reports.</li>
    <li>Synthetic fine-tuning that lets 1&ndash;8B models approach the strongest unadapted model at 84&ndash;87% lower token cost, running locally.</li>
  </ul>

  <h2 class="section-title">📝 Citation</h2>
  <pre style="background:#f8f9fa; padding:1rem; border-radius:8px;">@unpublished{tanveer2026lungnodule,
  title  = {Development and Validation of a Large Language Model for Generating Fully-Structured Lung Nodule Reports},
  author = {Tanveer, Md Sayed and Islam, Md Zabirul and Niu, Chuang and Kaviani, Parisa and Lyu, Qing and
            Kalra, Mannudeep K. and Whitlow, Christopher T. and Wang, Ge},
  note   = {Submitted to JAMIA. Equal contribution: M. S. Tanveer and M. Z. Islam},
  year   = {2026}
}</pre>

</main>
</div>

<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><span class="faux-block"><i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2026 Md Zabirul Islam</span></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>

</body></html>